# Generated by Django 5.0.1 on 2024-01-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_name_ru_category_name_tk'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_tk',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tk',
            field=models.TextField(null=True, verbose_name='title'),
        ),
    ]
