# Generated by Django 5.0.1 on 2024-01-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_news_description_ru_news_description_tk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_tk',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_tk',
        ),
    ]
