# Generated by Django 5.0.1 on 2024-01-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_news_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_tk',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tk',
            field=models.TextField(null=True, verbose_name='title'),
        ),
    ]
